version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/portfolio
permissions:
    - object: /var/www/portfolio
      pattern: "**"
      owner: apache
      group: apache
      mode: 755
      type:
        - file
hooks:
    BeforeInstall:
     - location: scripts/before_install.sh
       runas: root